---
language: python

python:
  - '3.7'

jobs:
  include:
    - stage: Linting
      install: 'pip install flake8'
      script: flake8
    - stage: Generate Database
      if: branch = master
      install:
        - 'pip install --upgrade pip pipenv'
        - 'pipenv install --system --deploy'
      before_script:
        - 'curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter'
        - 'chmod +x ./cc-test-reporter'
        - './cc-test-reporter before-build'
      script:
        - 'python main.py'
        - 'gzip --verbose clean_data/base156.sqlite'
        - 'pipenv lock -r --dev > requirements.txt'
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH
        file_glob: true
        file: clean_data/*
        skip_cleanup: true
        draft: true
