---
language: python

python:
  - 3.7
env:
  global:
    CC_TEST_REPORTER_ID=$CODECLIMATE_REPORTER_ID

branches:
  only:
    - master

jobs:
  include:
    - stage: Base linting
      install: pip install flake8
      script: flake8 app.py

    - stage: CI - Test Codebase - Quality Gate
      install:
        - pip install pytest coverage pytest-cov flake8
      script:
        - pytest --cov=curitiba156

    - stage: CD - Deploy
      if: branch = master
      install:
        - docker pull code4cwb/datascience-kit
      script:
        - docker run -it -v $(pwd):/app code4cwb/datascience-kit bash deploy.sh;
      before_deploy:
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export GIT_TAG=$(cat VERSION)-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
        - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
        - git push -q https://$GITHUB_OAUTH@github.com/joepreludian/recrutatech_devops_ia --tags
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH
        file_glob: true
        file: clean_data/*
        skip_cleanup: true
