---
language: python

python:
  - '3.7'

jobs:
  include:
    - stage: Linting
      install: 'pip install flake8'
      script: flake8
    - stage: Generate Database
      if: branch = master
      install:
        - 'pip install --upgrade pip pipenv'
        - 'pipenv install --system --deploy'
      script:
        - 'python main.py'
        - 'gzip --verbose clean_data/base156.sqlite'
    - stage: Deploy
      provider: releases
      api_key: $GITHUB_OAUTH
      file_glob: true
      file: clean_data/*
      skip_cleanup: true
