---
language: python

python:
  - 3.7

branches:
  only:
    - master

jobs:
  include:
    - stage: Base linting
      install: pip install flake8
      script: flake8 app.py

    - stage: CI - Test Codebase - Quality Gate
      install:
        - docker pull code4cwb/datascience-kit
      script:
        - docker run -it -v $(pwd):/app code4cwb/datascience-kit ./deploy.sh;
    
    - stage: CD - Deploy
      if: branch = master
      install:
        - docker pull code4cwb/datascience-kit
        - pip install codecov
      script:
        - docker run -it -v $(pwd):/app code4cwb/datascience-kit ./deploy.sh;
        - codecov
      before_deploy:
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export GIT_TAG=$(cat VERSION)-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
        - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
        - git push -q https://$GITHUB_OAUTH@github.com/CodeForCuritiba/ds-curitiba-dados-abertos --tags
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH
        file_glob: true
        file: clean_data/*
        skip_cleanup: true
